letters/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('letters/<ordering>/', LetterList.as_view(), name='letter_list'),
    path('search/admin/<query_text>/', SearchLettersAdmin.as_view(), name='admin_search'),
    path('search/user/<query_text>/', SearchLettersUser.as_view(), name='user_search'),
    path('letter/admin/<int:pk>/', AdminLetterDetail.as_view(), name='admin_letter'),
    path('letter/user/<int:pk>/', UserLetterDetail.as_view(), name='user_letter'),
]

app_name = 'letters'

usertools/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('selected/', user_selected, name='user_selected'),

    # admin paths
    path('admin/letters/<ordering>/', AdminPageLetters.as_view(), name='admin_letters'),
    path('admin/users/', AdminPageUsers.as_view(), name='admin_users'),
    path('clear_user_letters/<int:pk>/', clear_user_letters, name='clear_user_letters'),

    # auth paths
    path('logout/', logout_view, name='logout'),
    path('login/', LoginPage.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<uidb64>/<token>/', ConfirmEmail.as_view(), name='do_confirm_email'),
    path('info/email_was_send/', email_was_send, name='email_was_send'),

    path('update/gift/<int:gift_id>/<str:status>/', update_gift),
    path('update/letter/picked_by/<int:pk>/', add_favorite, name='pick_letter'),
    path('excel/save/file/', db_to_excel, name='saveexcel'),
    path('favorites/', favorite_page, name='favorites'),
    path('delete/favorites/<str:favorites>/', remove_list_favorites),
    path('favorites_to_selected/<str:favorites>/', favorites_to_selected),
    path('recommend_goods/<int:gift_pk>/', RecommendGoodsView.as_view(), name='recommend_goods'),
    path('get_recommend_goods/<int:pk>/', get_recommend_goods)
]

app_name = 'usertools'

wishtree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

from letters.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('letters/', include('letters.urls')),
    path('usertools/', include('usertools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usertools/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class BaseUser(AbstractUser):
    username = None
    phone = models.CharField('Телефон', max_length=20)
    email = models.EmailField('e-mail', unique=True)
    email_is_verified = models.BooleanField('e-mail подтверждён', default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def get_full_name(self):
        last_name = self.last_name or ''
        first_name = self.first_name or ''
        return f'{first_name} {last_name}'

    def __str__(self):
        return f'Имя: {self.first_name}, Фамилия: {self.last_name}'

usertools/forms.py
from django.contrib.auth.forms import UserCreationForm

from usertools.models import BaseUser


class RegisterForm(UserCreationForm):

    class Meta:
        model = BaseUser
        fields = ('email', 'phone', 'first_name', 'last_name', 'password1', 'password2')


# class RegisterForm(forms.ModelForm):
#     first_name = forms.CharField(label='Имя')
#     last_name = forms.CharField(label='Фамилия')
#     email = forms.EmailField(label='Введите email')
#     phone = forms.CharField(label='Введите телефон')
#     password = forms.CharField(label='Введите пароль', widget=forms.PasswordInput)
#     password_repeat = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
#
#     def clean(self):
#         self.validate_password()
#         clean_first_name = self.cleaned_data['first_name'].replace(' ', '')
#         clean_last_name = self.cleaned_data['last_name'].replace(' ', '')
#         clean_username = (
#             f"{clean_first_name}{clean_last_name}"
#         )
#         if re.match(r'\W', clean_username):
#             raise ValidationError('Имя и Фамилия должны содержать тольок буквенные символы')
#         elif re.findall(r'[а-я]+', clean_username.lower())[0] != clean_username.lower():
#             raise ValidationError('Имя и Фамили должны содержать только символы кирилицы')
#
#         self.cleaned_data['username'] = clean_username
#         self.cleaned_data.pop('last_name')
#         self.cleaned_data.pop('first_name')
#         self.cleaned_data.pop('password_repeat')
#
#         return self.cleaned_data
#
#     def validate_password(self):
#         password = self.cleaned_data['password']
#         has_upper_case = password.lower() != password
#
#         if not self.cleaned_data['password'] == self.cleaned_data['password_repeat']:
#             raise ValidationError('Пароли не совпадают')
#         elif (len(self.cleaned_data['password']) < 8) or has_upper_case or re.match(r'\w', password):
#             return ValidationError(
#                 'Парль должен быть 8 или более символов, содержать мадые и заглавне буквы'
#             )

usertools/views.py
from django.contrib.auth import logout, login, get_user_model
from django.contrib.auth.models import Permission
from django.db.models import Count
from django.http import HttpResponse, Http404, JsonResponse
from django.views.generic import CreateView, View, DetailView
from django.contrib.auth.views import LoginView, AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.utils.http import urlsafe_base64_decode
from django.core.exceptions import ValidationError

from letters.models import Letter, Gift

from .utils import DbToExcel, ConfirmEmailMixin, RecommendGoods
from .forms import RegisterForm

from wishtree.settings import BASE_DIR


User = get_user_model()


# Auth views
class LoginPage(LoginView, ConfirmEmailMixin):
    form_class = AuthenticationForm
    template_name = 'usertools/login.html'

    def form_valid(self, form):
        user = form.get_user()

        if not user.email_is_verified:
            self.send_confirm_email(user)
            return redirect('usertools:email_was_send')

        login(self.request, user)
        return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('index')


class RegisterView(CreateView, ConfirmEmailMixin):
    form_class = RegisterForm
    template_name = 'usertools/register.html'

    def form_valid(self, form):
        user = form.save()
        self.send_confirm_email(user)
        return redirect('usertools:email_was_send')


class ConfirmEmail(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if not (user is not None and token_generator.check_token(user, token)):
            raise Http404('Данные для подтверждения email оказались неверны, попробуйте войти снова')
            
        user.email_is_verified = True
        user.save()
        login(request, user)
        response = redirect('index')

        return response

    @staticmethod
    def get_user(uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user
# End auth views


def email_was_send(request):
    return render(request, 'usertools/email_was_send.html')


def user_selected(request):
    context = {}

    if request.user.is_authenticated:
        letters = Letter.objects.filter(
            picked_by=request.user
        ).prefetch_related('gift').prefetch_related('child')

        if letters.exists():
            context['letters'] = letters
        else:
            context['empty_object_text'] = 'info/need_select_selected.html'
    else:
        context['empty_object_text'] = 'info/need_login.html'

    return render(request, 'usertools/selected_gifts.html', context)


# admin views
class AdminPageLetters(View):

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponse(status=403)

        ordering = self.kwargs['ordering']
        letters = Letter.objects.all()
        if not ordering == 'all':
            letters = letters.filter(gift__status=Gift.GIFT_STATUS_CHOICES[int(ordering)][0])

        return render(request, 'usertools/admin_letters.html', {'letters': letters, 'ordering': ordering})


class AdminPageUsers(View):

    @staticmethod
    def get(request):
        if not request.user.is_staff:
            return HttpResponse(status=403)

        users = User.objects.filter(letters__isnull=False).annotate(
            num_letters=Count('letters')
        ).order_by('-num_letters')

        return render(request, 'usertools/admin_users.html', {'users': users})


def clear_user_letters(request, pk):
    if not request.user.is_staff:
        return HttpResponse(status=403)

    user = User.objects.get(pk=pk)
    user.letters.set([])
    cannot_select_letters = Permission.objects.get(codename='cannot_select_letters')
    user.user_permissions.add(cannot_select_letters)

    return redirect('usertools:admin_users')
# end admin views


def update_gift(request, gift_id, status):
    status = Gift.GIFT_STATUS_CHOICES[int(status)][0]
    gift = Gift.objects.filter(pk=gift_id)

    if status == 'unselect':
        Letter.objects.filter(gift=gift.first()).update(picked_by=None)

    gift.update(status=status)
    return HttpResponse(status=200)


def add_favorite(request, pk):
    if request.user.has_perm('usertools.cannot_select_letters'):
        return HttpResponse('cannot_select_letters', status=403)

    if not request.user.is_authenticated:
        return redirect('usertools:login')

    if request.user.letters.exists():
        return redirect('usertools:favorites')

    letter = Letter.objects.get(pk=pk, gift__status='unselect')
    request.user.favorites.add(letter.pk)

    return HttpResponse(status=200)


def remove_list_favorites(request, favorites):
    clean_favorites = favorites.strip().split(',')
    # check if letter not have in user favorites
    for letter in clean_favorites:
        request.user.favorites.remove(letter)

    return HttpResponse(status=200)


def favorites_to_selected(request, favorites):
    favorites = favorites.strip().split(',')

    request.user.letters.set(Letter.objects.filter(pk__in=favorites))
    for letter in request.user.letters.prefetch_related('gift'):
        letter.gift.status = 'selected'

    request.user.favorites.set([])
    request.user.save()

    return redirect('usertools:user_selected')


def db_to_excel(request):
    if not request.user.is_superuser:
        return HttpResponse(status=403)

    excel_file = BASE_DIR / 'media' / 'excel' / 'excel_table.xlsx'
    DbToExcel().write_to_excel(excel_file)

    with excel_file.open('rb') as f:
        response = HttpResponse(f.read(), content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'inline; filename=excel_table.xlsx'
        return response


def favorite_page(request):
    context = {}
    if not request.user.is_authenticated:
        context['empty_object_text'] = 'info/need_login.html'
    else:
        favorites = request.user.favorites
        if favorites.exists():
            context['letters'] = favorites
        else:
            if request.user.letters.exists():
                context['empty_object_text'] = 'info/already_select.html'
            else:
                context['empty_object_text'] = 'info/need_select_favorites.html'

    return render(request, 'usertools/favorites.html', context)


class RecommendGoodsView(DetailView):
    model = Gift
    template_name = 'usertools/recommend.html'
    pk_url_kwarg = 'gift_pk'
    context_object_name = 'gift'


def get_recommend_goods(request, pk):
    gift = Gift.objects.get(pk=pk)
    dependency = RecommendGoods(gift=gift.name)
    print(type(dependency.shops))
    print(type(dependency.goods))
    return JsonResponse({'goods': dependency.goods, 'shops': dependency.shops})

usertools/templates/usertools/admin_letters.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Администрирование писем | Ёлка добра</title>
    <meta name="viewport" content>

    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/selects.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/admin-page.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
</head>
<body>
<p id="successGiftChange" class="popup-message" style="display: none"></p>

<div style="
background: url({% static 'letters/images/santa.gif' %});
background-size: var(--santa-width);
" id="santa"></div>

<div class="page">
    {% include 'components/admin_header.html' %}

    <div class="ordering-container">
        <div class="ordering">
            <div class="ordering-banner">
                <img class="ordering-banner-img" src="{% static 'letters/images/order.png' %}">
                <p style="margin-left: .4em">Сортировать</p>
            </div>
            <select class="letter-ordering">
                <option class="ordering-option" value="all">Все</option>
                <option class="ordering-option" value="0">Не выбраные</option>
                <option class="ordering-option" value="1">Выбраные</option>
                <option class="ordering-option" value="2">Доставленые</option>
            </select>
        </div>
        <div class="queryset-select">
            <div class="queryset-option queryset-selected-option">
                <a href="{% url 'usertools:admin_letters' ordering='all' %}">
                    <span class="queryset-text">Письма</span>
                </a>
            </div>
            <div class="queryset-option queryset-unselected-option">
                <a href="{% url 'usertools:admin_users' %}">
                    <span class="queryset-text">Пользователи</span>
                </a>
            </div>
        </div>
    </div>

    <div class="letters high-element">
        {% for letter in letters %}
            <div class="letter-container">
                {% if letter.gift.status == 'unselect' %}
                <div class="letter orange-card">
                {% elif letter.gift.status == 'selected' %}
                <div class="letter blue-card">
                {% else %}
                <div class="letter green-card">
                {% endif %}
                    <img class="letter-el letter-img" src="{{ letter.photo.url }}">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    <div class="custom-select letter-el">
                        <select data-objectid="{{ letter.gift.pk }}" name="status-select" style="margin-top: 7px">
                            <option value="0"
                            {% if letter.gift.status == 'unselect' %}selected{% endif %}
                            >Не выбранно</option>
                            <option value="2"
                            {% if letter.gift.status == 'delivered' %}selected{% endif %}
                            >Доставленно</option>
                            <option value="1"
                            {% if letter.gift.status == 'selected' %}selected{% endif %}
                            >Выбрано</option>
                        </select>
                    </div>
                    <a
                        class="letter-el"
                        href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                    >
                        <button class="default-button inner-button">
                            <span>Подобрать подарок</span>
                        </button>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% include 'components/footer.html' %}

<script src="{% static 'letters/js/burgerMenu.js' %}"></script>
<script src="{% static 'letters/js/script.js' %}"></script>
<script src="{% static 'usertools/js/changeGiftState.js' %}"></script>
<script>
document.querySelector('select.letter-ordering').value = '{{ ordering }}'

document.querySelector('select.letter-ordering').addEventListener('change', (event) => {
  let param = event.target.options[event.target.selectedIndex].value
  window.location.href = `${url}/usertools/admin/letters/${param}`
})
</script>

</body>
</html>

usertools/templates/usertools/admin_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Администрирование писем | Ёлка добра</title>
    <meta name="viewport" content>

    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/selects.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/admin-page.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
</head>
<body>
{% include 'components/confirm_message.html' with text='Вы уверены, что хотите отчистить выбранные письма для этого пользователя?' custom_class='clean-user-letters-message' %}

<div class="page">
    {% include 'components/admin_header.html' %}

    <div class="ordering-container" style="justify-content: flex-end">
        <div class="queryset-select">
            <div class="queryset-option queryset-unselected-option">
                <a href="{% url 'usertools:admin_letters' ordering='all' %}">
                    <span class="queryset-text">Письма</span>
                </a>
            </div>
            <div class="queryset-option queryset-selected-option">
                <a href="{% url 'usertools:admin_users' %}">
                    <span class="queryset-text">Пользователи</span>
                </a>
            </div>
        </div>
    </div>

    <p id="successGiftChange" class="popup-message" style="display: none"></p>

    <div class="users high-element">
        {% for user in users %}
            <div class="user-container">
                <div class="user-text-container">
                    <span class="user-el username">{{ user.get_full_name }}</span>
                    <p class="user-el" style="margin: 0">
                        {% if user.phone %}
                        <span class="user-contact">{{ user.phone }}</span>
                        {% endif %}
                        <span class="user-contact">{{ user.email }}</span>
                    </p>
                    <span class="user-el">Выбранно писем: {{ user.num_letters }}</span>
                </div>
                <div class="user-link">
                    <a class="clean-letters-link" data-href="{% url 'usertools:clear_user_letters' pk=user.pk %}">
                        <img src="{% static 'usertools/images/delete.png' %}" class="icon">
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% include 'components/footer.html' %}

<script src="{% static 'letters/js/burgerMenu.js' %}"></script>
<script src="{% static 'letters/js/script.js' %}"></script>
<script src="{% static 'letters/js/confirmMessage.js' %}"></script>
<script src="{% static 'usertools/js/changeGiftState.js' %}"></script>
<script>
setConfirmMessage(
  document.querySelectorAll('a.clean-letters-link'),
  'clean-user-letters-message'
)
</script>

</body>
</html>

usertools/templates/usertools/confirm_email_text.html
{% autoescape off %}

Здратсвуйте, {{ user.get_full_name }}
Пожалйста, перейдите по ссылке, чтобы завершить регестрацию
{{ request.scheme }}://{{ domain }}{% url 'usertools:do_confirm_email' uidb64=uid token=token %}
Если вы не регестрировались на этом сайте, просто проигнорируйте это сообщение

{% endautoescape %}

usertools/templates/usertools/email_was_send.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Подтверждение почты | Ёлка добра</title>
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
</head>
<body>

<h2 style="display: flex; height: 100vh; justify-content: center; align-items: center">
    <span>
        На вашу почту пришло письмо,
        пожалуйста перейдите по ссылке в письме для подтвержения регестрации.
    </span>
</h2>

</body>
</html>

usertools/templates/usertools/favorites.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Избранные письма | Ёлка добра</title>

    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/favorites.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/empty-object.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{% static 'letters/css/medias.css' %}">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
</head>
<body style="background-image: url('{% static 'letters/images/sitebg.jpg' %}')">
{% include 'components/confirm_message.html' with text='Вы уверены, что хотите забронировать выбраные письма, изменить свой выбор после будет невозможно!' custom_class='select-all-letters-confirm-message' %}

<div class="page">
    {% include 'components/user_header.html' %}

    {% if letters %}

        <div class="favorites-block high-element">
            <div class="favorites-list">
                <div class="favorites-controls">
                    <div class="default-checkbox">
                        <input type="checkbox" checked class="default-checkbox" id="select-all-checkbox">
                        <label for="select-all-checkbox">Выбрать все</label>
                    </div>
                    <div class="delete-button" id="delete-all-button">
                        <img src="{% static 'usertools/images/x.png' %}" class="delete-icon">
                        <span class="delete-button-text">Удалить все</span>
                    </div>
                </div>

                <div class="favorites">
                    {% for letter in letters.all %}
                        <div class="favorite" data-objectid="{{ letter.pk }}">
                            <div><img class="favorite-img letter-img" src="{{ letter.photo.url }}"></div>
                            <div class="favorite-content">
                                <div class="favorite-content-text">
                                    <span>Подарок: {{ letter.gift.name }}</span>
                                    <span class="second-favorite-text">{{ letter.child.full_name }}</span>
                                </div>
                                <div class="favorite-el-controls">
                                    <div class="default-checkbox">
                                        <input type="checkbox" checked name="letter-checkbox" id="letter-checkbox{{ letter.pk }}">
                                        <label for="letter-checkbox{{ letter.pk }}"></label>
                                    </div>
                                    <div class="delete-button delete-favorite">
                                        <img src="{% static 'usertools/images/x.png' %}" class="delete-icon">
                                        <span class="delete-button-text">Удалить</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="select-all">
                <div class="select-all-container">
                    <button class="default-button select-all-button">Забронировать</button>
                    <p class="warning-text">
                        После того, как вы выберите подарки, их больше нельзя будет изменить!
                    </p>
                </div>
            </div>
        </div>

        <script src="{% static 'letters/js/confirmMessage.js' %}"></script>
        <script>
            setVisitedMessage(
              'favorite-visited',
              'Подсказка при первом заходе на страницу'
            )
            setConfirmMessage(
              document.querySelectorAll('button.select-all-button'),
              'select-all-letters-confirm-message'
            )
        </script>
    {% else %}
        {% include empty_object_text %}
    {% endif %}
</div>

{% include 'components/footer.html' %}

<script src="{% static 'usertools/js/favorites.js' %}"></script>
</body>
</html>

usertools/templates/usertools/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход на сайт | Ёлка добра</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/login.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
</head>
<body>

  <div class="page">
    {% include 'components/user_header.html' %}

    <div class="form-wrapper">
      <form method="post" class="login-form">
        <div class="title-block">
          <span class="form-title">Вход</span>
          <div class="sub-text">
            <a href="{% url 'usertools:register' %}">Регестрация</a>
          </div>
        </div>

        {% csrf_token %}
        {{ form.as_p }}
        <button class="default-button" type="submit">Отправить</button>
      </form>
  </div>
</div>
{% include 'components/footer.html' %}

<script src="{% static 'letters/js/userindex.js' %}"></script>
<script src="{% static 'usertools/js/labelToPlaceholder.js' %}"></script>
</body>
</html>

usertools/templates/usertools/selected_gifts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мои подарки | Ёлка добра</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/selected-gifts.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/empty-object.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
</head>
<body>

<div class="page">
    {% include 'components/user_header.html' %}

    {% if letters %}
    <div class="address-container">
        <p class="address-text">Текст, который подсказывает, куда нужно принести подарок.</p>
    </div>

    <div class="letters">
        {% for letter in letters %}
            <div class="letter-container">
                <div class="letter {% if letter.gift.status == 'selected' %}blue-card{% else %}green-card{% endif %}">
                    <img class="letter-el letter-img" src="{{ letter.photo.url }}" alt="letter-img">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    <p class="letter-el">{{ request.user.first_name }}</p>
                    <a
                        class="letter-el"
                        href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                    >
                        <button class="default-button inner-button">
                            <span>Подобрать подарок</span>
                        </button>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
    setVisitedMessage(
      'index-visited',
      'Подсказка при первом заходе на страницу'
    )
    </script>
    {% else %}
        {% include empty_object_text %}
    {% endif %}
</div>

{% include 'components/footer.html' %}
</body>
</html>