letters/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('letters/<ordering>/', LetterList.as_view(), name='letter_list'),
    path('search/admin/<query_text>/', SearchLettersAdmin.as_view(), name='admin_search'),
    path('search/user/<query_text>/', SearchLettersUser.as_view(), name='user_search'),
    path('letter/admin/<int:pk>/', AdminLetterDetail.as_view(), name='admin_letter'),
    path('letter/user/<int:pk>/', UserLetterDetail.as_view(), name='user_letter'),
]

app_name = 'letters'

usertools/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('selected/', user_selected, name='user_selected'),

    # admin paths
    path('admin/letters/<ordering>/', AdminPageLetters.as_view(), name='admin_letters'),
    path('admin/users/', AdminPageUsers.as_view(), name='admin_users'),
    path('clear_user_letters/<int:pk>/', clear_user_letters, name='clear_user_letters'),

    # auth paths
    path('logout/', logout_view, name='logout'),
    path('login/', LoginPage.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<uidb64>/<token>/', ConfirmEmail.as_view(), name='do_confirm_email'),
    path('info/email_was_send/', email_was_send, name='email_was_send'),

    path('update/gift/<int:gift_id>/<str:status>/', update_gift),
    path('update/letter/picked_by/<int:pk>/', add_favorite, name='pick_letter'),
    path('excel/save/file/', db_to_excel, name='saveexcel'),
    path('favorites/', favorite_page, name='favorites'),
    path('delete/favorites/<str:favorites>/', remove_list_favorites),
    path('favorites_to_selected/<str:favorites>/', favorites_to_selected),
    path('recommend_goods/<int:gift_pk>/', RecommendGoodsView.as_view(), name='recommend_goods'),
    path('get_recommend_goods/<int:pk>/', get_recommend_goods)
]

app_name = 'usertools'

wishtree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

from letters.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('letters/', include('letters.urls')),
    path('usertools/', include('usertools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

letters/models.py
from django.db import models
from django.urls import reverse

from wishtree.settings import AUTH_USER_MODEL


class Child(models.Model):
    name = models.CharField('Имя', max_length=255)
    age = models.PositiveSmallIntegerField('Возвраст')

    def __str__(self):
        return self.name

    def get_full_name(self) -> str:
        return f'{self.name}, {self.age} лет'

    class Meta:
        verbose_name = 'Ребёнок'
        verbose_name_plural = 'Дети'


class Gift(models.Model):

    UN = 'unselect'
    S = 'selected'
    DEL = 'delivered'

    GIFT_STATUS_CHOICES = [
        (UN, 'Ещё не выбрано'),
        (S, 'Выбрано'),
        (DEL, 'Доставлено')
    ]

    name = models.CharField('Название подарка', max_length=99)
    status = models.CharField('Состояние подарка', max_length=99, choices=GIFT_STATUS_CHOICES, default=UN)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подарок'
        verbose_name_plural = 'Подарки'


class Letter(models.Model):
    picked_by = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='letters', null=True, blank=True
    )
    favorite_select = models.ManyToManyField(AUTH_USER_MODEL, related_name='favorites', blank=True)
    child = models.OneToOneField(Child, on_delete=models.CASCADE, null=True, blank=True)
    gift = models.OneToOneField(Gift, on_delete=models.PROTECT)
    photo = models.FileField('Письмо', upload_to='images/letter/')

    def get_user_to_excel(self):
        full_name = self.picked_by.get_full_name()
        phone = self.picked_by.phone or ''
        email = self.picked_by.email

        return {'email': email, 'full_name': full_name, 'phone': phone}

    def __str__(self):
        return f'Письмо номер {self.pk}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'

letters/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DetailView

from .models import Gift
from .utils import Letter, SearchMethods, FavoritesMixin


def index(request):
    if request.user.is_staff:
        return redirect('usertools:admin_letters', ordering='all')

    letters = Letter.objects.all()
    if request.user.is_authenticated:
        pks = request.user.favorites.values_list('pk', flat=True)
        letters = letters.filter(~Q(pk__in=pks))

    return render(request, 'letters/index.html', {'letters': letters})


class LetterList(FavoritesMixin, ListView):
    model = Letter
    template_name = 'letters/letters.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        ordering = self.kwargs['ordering']
        letters = self.exclude_favorite_letters()
        if not ordering == 'all':
            letters = letters.filter(gift__status=Gift.GIFT_STATUS_CHOICES[int(ordering)][0])
        context['letters'] = letters
        context['ordering'] = ordering

        return context


class SearchLettersAdmin(SearchMethods, View):

    def get(self, request, query_text):
        letters_by_user = self.search_by_user(query_text)
        letters_by_child = self.search_by_child(query_text)
        letters_by_gift = self.search_by_gift(query_text)

        return JsonResponse(
            {
                'letters_by_user': letters_by_user,
                'letters_by_child': letters_by_child,
                'letters_by_gift': letters_by_gift
            }
        )

    @staticmethod
    def search_by_user(query_text):
        letters = Letter.objects.filter(
            picked_by__first_name__icontains=query_text
        ).values('pk', 'picked_by__first_name')

        return list(letters)


class SearchLettersUser(SearchMethods, View):

    def get(self, request, query_text):
        letters_by_child = self.search_by_child(query_text)
        letters_by_gift = self.search_by_gift(query_text)

        return JsonResponse(
            {'letters_by_child': letters_by_child, 'letters_by_gift': letters_by_gift, 'letters_by_user': []}
        )


class AdminLetterDetail(DetailView):
    model = Letter
    template_name = 'letters/admin_letter.html'
    context_object_name = 'letter'

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponse(status=403)
        return super().get(request, *args, **kwargs)


class UserLetterDetail(DetailView):
    model = Letter
    template_name = 'letters/user_letter.html'
    context_object_name = 'letter'

letters/templates/components/admin_header.html
{% load static %}
<header id="admin_header">
  <ul id="burger-menu">
    {% if request.user.is_authenticated %}
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'usertools:logout' %}">Выйти</a>
    </li>
    {% endif %}
    <li class="burger-menu-item">
      <a class="burger-item-text" href="/admin">
        <span>Панель администратора</span>
        <img class="burger-item-img icon" src="{% static 'letters/images/admin.png' %}">
      </a>
    </li>
    {% if request.user.is_superuser %}
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'usertools:saveexcel' %}" download="">
        <span>Сохранить excel</span>
        <img class="burger-item-img icon" src="{% static 'usertools/images/excel.png' %}">
      </a>
    </li>
    {% endif %}
    <li class="burger-menu-item search-button">
      <span class="burger-item-text">Искать</span>
      <img class="icon burger-item-img" src="{% static 'letters/images/search.png' %}" alt="gifts">
    </li>
  </ul>

  <p class="logo-block" style="margin-top: 0">
    <a href="{% url 'usertools:admin_letters' ordering='all' %}">
      <img class="logo" src="{% static 'letters/images/christmas-tree.png' %}" alt="logo">
    </a>
  </p>
  <div class="search-container" style="display: none">
    <div class="back-arrow">
      <img class="icon" src="{% static 'letters/images/back-arrow.png' %}">
    </div>
    <input class="search-input" type="text" placeholder="Искать письмо">
    <ul class="search-results"></ul>
  </div>
  <nav>
    <a class="nav-link button-link burger-hidden" href="/admin">
      <button class="default-button block-button">
        <span>Панель администратора</span>
        <img class="icon" src="{% static 'letters/images/admin.png' %}" alt="gifts">
      </button>
    </a>
    {% if request.user.is_superuser %}
    <a class="nav-link button-link burger-hidden" href="{% url 'usertools:saveexcel' %}" download="">
      <button class="default-button block-button">
        <span>Сохранить excel</span>
        <img class="icon" src="{% static 'usertools/images/excel.png' %}">
      </button>
    </a>
    {% endif %}
    <a class="nav-link burger-hidden search-button">
      <button class="block-button default-button">
        <span class="el-text">Искать</span>
        <img class="icon el-image" src="{% static 'letters/images/search.png' %}" alt="gifts">
      </button>
    </a>
    <p><span>{{ request.user.get_full_name }}</span></p>
    <p class="text-link burger-hidden"><a href="{% url 'usertools:logout' %}">Выйти</a></p>
    <div id="burger-block">
      <img src="{% static 'usertools/images/burger.png' %}">
    </div>
  </nav>
</header>

<script src="{% static 'letters/js/fetchSearchResult.js' %}"></script>

letters/templates/components/confirm_message.html
<div class="confirm-message-container {{ custom_class }}" style="display: none">
    <div class="confirm-message">
        <span class="confirm-message-text">{{ text }}</span>
        <div class="confirm-message-buttons">
            <div class="confirm-message-button-container confirm-message-decline-container">
                <button class="decline-button">Нет</button>
            </div>
            <div class="confirm-message-button-container confirm-message-confirm-container">
                <button class="confirm-button">Да</button>
            </div>
        </div>
    </div>
</div>

letters/templates/components/footer.html
{% load static %}
<footer>
    <p class="footer-el copyright">
        <span>Copyright text © 2022</span>
    </p>
    <p class="footer-el contact-block">
        <span class="contact-data contact-data-text">
            <span>Контактные данные:</span>
        </span>
        <span class="contact-data ">8 (000) 000 00-00</span>
        <span class="contact-data">email@email.com</span>
    </p>
</footer>

letters/templates/components/user_header.html
{% load static %}
<header id="user_header">
  <ul id="burger-menu">
    {% if request.user.is_authenticated %}
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'usertools:logout' %}">Выйти</a>
    </li>
    {% endif %}
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'letters:letter_list' ordering='all' %}">
        <span>Все письма</span>
        <img class="icon burger-item-img" src="{% static 'letters/images/letters.png' %}">
      </a>
    </li>
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'usertools:user_selected' %}">
        <span>Мои подарки</span>
        <img class="icon burger-item-img" src="{% static 'letters/images/giftbox.png' %}">
      </a>
    </li>
    <li class="burger-menu-item search-button">
      <span class="burger-item-text">Искать</span>
      <img class="icon burger-item-img" src="{% static 'letters/images/search.png' %}">
    </li>
    <li class="burger-menu-item">
      <a class="burger-item-text" href="{% url 'usertools:favorites' %}">
        <span>Избранное</span>
        <img class="icon burger-item-img" src="{% static 'usertools/images/favorite.png' %}">
      </a>
    </li>
  </ul>

  <p class="logo-block" style="margin-top: 0">
    <a href="{% url 'index' %}">
      <img class="logo" src="{% static 'letters/images/christmas-tree.png' %}" alt="logo">
    </a>
  </p>
  <div class="search-container" style="display: none">
    <div class="back-arrow">
      <img src="{% static 'letters/images/back-arrow.png' %}">
    </div>
    <input class="search-input" type="text" placeholder="Искать письмо">
    <ul class="search-results"></ul>
  </div>
  <nav>
    <a class="nav-link burger-hidden" href="{% url 'letters:letter_list' ordering='all' %}">
      <button class="default-button block-button">
        <span>Все письма</span>
        <img class="icon" src="{% static 'letters/images/letters.png' %}" alt="gifts">
      </button>
    </a>
    <a class="nav-link burger-hidden" href="{% url 'usertools:user_selected' %}">
      <button class="default-button block-button">
        <span>Мои подарки</span>
        <img class="icon" src="{% static 'letters/images/giftbox.png' %}" alt="gifts">
      </button>
    </a>
    <a class="nav-link burger-hidden search-button">
      <button class="block-button default-button">
        <span class="el-text">Искать</span>
        <img class="icon el-image" src="{% static 'letters/images/search.png' %}" alt="gifts">
      </button>
    </a>
    <a class="nav-link burger-hidden" href="{% url 'usertools:favorites' %}">
      <button class="block-button default-button">
        <span class="el-text">Избранное</span>
        <img class="icon el-image" src="{% static 'usertools/images/favorite.png' %}" alt="gifts">
      </button>
    </a>
    {% if request.user.is_authenticated %}
      <p class="nav-el"><span>{{ request.user.get_full_name }}</span></p>
      <p class="nav-el burger-hidden"><a href="{% url 'usertools:logout' %}">Выйти</a></p>
    {% else %}
      <p class="nav-el">
        <a href="{% url 'usertools:register' %}">Регистрация</a>
        <a id="login-text" href="{% url 'usertools:login' %}">Вход</a>
      </p>
    {% endif %}
    <div id="burger-block">
      <img src="{% static 'usertools/images/burger.png' %}">
    </div>
  </nav>
</header>

<div class="helper helper-limited">
    <div class="helper-img-container helper-el">
        <img class="helper-img" src="{% static 'letters/images/helper.png' %}"">
    </div>
    <div class="info-message helper-el" style="display: none">
        <img class="helper-x-img helper-content" src="{% static 'usertools/images/x.png' %}">
        <span class="message-text helper-content"></span>
    </div>
    <div class="hints-swiper helper-el helper-content" style="display: none">
        <div class="swiper-wrapper"></div>
    </div>
</div>

<script src="{% static 'letters/js/script.js' %}"></script>
<script src="{% static 'letters/js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'usertools/js/userheader.js' %}"></script>
<script src="{% static 'letters/js/fetchSearchResult.js' %}"></script>
<script src="{% static 'letters/js/burgerMenu.js' %}"></script>