letters/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('letters/<ordering>/', LetterList.as_view(), name='letter_list'),
    path('search/admin/<query_text>/', SearchLettersAdmin.as_view(), name='admin_search'),
    path('search/user/<query_text>/', SearchLettersUser.as_view(), name='user_search'),
    path('letter/admin/<int:pk>/', AdminLetterDetail.as_view(), name='admin_letter'),
    path('letter/user/<int:pk>/', UserLetterDetail.as_view(), name='user_letter'),
]

app_name = 'letters'

usertools/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('selected/', user_selected, name='user_selected'),

    # admin paths
    path('admin/letters/<ordering>/', AdminPageLetters.as_view(), name='admin_letters'),
    path('admin/users/', AdminPageUsers.as_view(), name='admin_users'),
    path('clear_user_letters/<int:pk>/', clear_user_letters, name='clear_user_letters'),

    # auth paths
    path('logout/', logout_view, name='logout'),
    path('login/', LoginPage.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<uidb64>/<token>/', ConfirmEmail.as_view(), name='do_confirm_email'),
    path('info/email_was_send/', email_was_send, name='email_was_send'),

    path('update/gift/<int:gift_id>/<str:status>/', update_gift),
    path('update/letter/picked_by/<int:pk>/', add_favorite, name='pick_letter'),
    path('excel/save/file/', db_to_excel, name='saveexcel'),
    path('favorites/', favorite_page, name='favorites'),
    path('delete/favorites/<str:favorites>/', remove_list_favorites),
    path('favorites_to_selected/<str:favorites>/', favorites_to_selected),
    path('recommend_goods/<int:gift_pk>/', RecommendGoodsView.as_view(), name='recommend_goods'),
    path('get_recommend_goods/<int:pk>/', get_recommend_goods)
]

app_name = 'usertools'

wishtree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

from letters.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('letters/', include('letters.urls')),
    path('usertools/', include('usertools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

letters/models.py
from django.db import models
from django.urls import reverse

from wishtree.settings import AUTH_USER_MODEL


class Child(models.Model):
    name = models.CharField('Имя', max_length=255)
    age = models.PositiveSmallIntegerField('Возвраст')

    def __str__(self):
        return self.name

    def get_full_name(self) -> str:
        return f'{self.name}, {self.age} лет'

    class Meta:
        verbose_name = 'Ребёнок'
        verbose_name_plural = 'Дети'


class Gift(models.Model):

    UN = 'unselect'
    S = 'selected'
    DEL = 'delivered'

    GIFT_STATUS_CHOICES = [
        (UN, 'Ещё не выбрано'),
        (S, 'Выбрано'),
        (DEL, 'Доставлено')
    ]

    name = models.CharField('Название подарка', max_length=99)
    status = models.CharField('Состояние подарка', max_length=99, choices=GIFT_STATUS_CHOICES, default=UN)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подарок'
        verbose_name_plural = 'Подарки'


class Letter(models.Model):
    picked_by = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='letters', null=True, blank=True
    )
    favorite_select = models.ManyToManyField(AUTH_USER_MODEL, related_name='favorites', blank=True)
    child = models.OneToOneField(Child, on_delete=models.CASCADE, null=True, blank=True)
    gift = models.OneToOneField(Gift, on_delete=models.PROTECT)
    photo = models.FileField('Письмо', upload_to='images/letter/')

    def get_user_to_excel(self):
        full_name = self.picked_by.get_full_name()
        phone = self.picked_by.phone or ''
        email = self.picked_by.email

        return {'email': email, 'full_name': full_name, 'phone': phone}

    def __str__(self):
        return f'Письмо номер {self.pk}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'

letters/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DetailView

from .models import Gift
from .utils import Letter, SearchMethods, FavoritesMixin


def index(request):
    if request.user.is_staff:
        return redirect('usertools:admin_letters', ordering='all')

    letters = Letter.objects.all()
    if request.user.is_authenticated:
        pks = request.user.favorites.values_list('pk', flat=True)
        letters = letters.filter(~Q(pk__in=pks))

    return render(request, 'letters/index.html', {'letters': letters})


class LetterList(FavoritesMixin, ListView):
    model = Letter
    template_name = 'letters/letters.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        ordering = self.kwargs['ordering']
        letters = self.exclude_favorite_letters()
        if not ordering == 'all':
            letters = letters.filter(gift__status=Gift.GIFT_STATUS_CHOICES[int(ordering)][0])
        context['letters'] = letters
        context['ordering'] = ordering

        return context


class SearchLettersAdmin(SearchMethods, View):

    def get(self, request, query_text):
        letters_by_user = self.search_by_user(query_text)
        letters_by_child = self.search_by_child(query_text)
        letters_by_gift = self.search_by_gift(query_text)

        return JsonResponse(
            {
                'letters_by_user': letters_by_user,
                'letters_by_child': letters_by_child,
                'letters_by_gift': letters_by_gift
            }
        )

    @staticmethod
    def search_by_user(query_text):
        letters = Letter.objects.filter(
            picked_by__first_name__icontains=query_text
        ).values('pk', 'picked_by__first_name')

        return list(letters)


class SearchLettersUser(SearchMethods, View):

    def get(self, request, query_text):
        letters_by_child = self.search_by_child(query_text)
        letters_by_gift = self.search_by_gift(query_text)

        return JsonResponse(
            {'letters_by_child': letters_by_child, 'letters_by_gift': letters_by_gift, 'letters_by_user': []}
        )


class AdminLetterDetail(DetailView):
    model = Letter
    template_name = 'letters/admin_letter.html'
    context_object_name = 'letter'

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponse(status=403)
        return super().get(request, *args, **kwargs)


class UserLetterDetail(DetailView):
    model = Letter
    template_name = 'letters/user_letter.html'
    context_object_name = 'letter'

letters/templates/letters/admin_letter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Просмотр письма | Ёлка Добра</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/admin-page.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letter-detail.css' %}" rel="stylesheet">
</head>

<body>

    <div class="page">
        {% include 'components/admin_header.html' %}
        <p id="successGiftChange" class="popup-message" style="display: none"></p>

        <div class="high-line high-element">
            <div class="back-arrow-on-page-container" onclick="window.history.back()">
                <img class="back-arrow-on-page" src="{% static 'letters/images/back-arrow.png' %}">
            </div>
        </div>

        <div class="letters high-element letters-mt">
            <div class="letter-container">
                {% if letter.gift.status == 'unselect' %}
                <div class="letter orange-card">
                {% elif letter.gift.status == 'selected' %}
                <div class="letter blue-card">
                {% else %}
                <div class="letter green-card">
                {% endif %}
                    <img class="letter-el" src="{{ letter.photo.url }}">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    <div class="custom-select letter-el">
                        <select data-objectid="{{ letter.gift.pk }}" name="status-select" style="margin-top: 7px">
                            <option value="0"
                            {% if letter.gift.status == 'unselect' %}selected{% endif %}
                            >Не выбранно</option>
                            <option value="2"
                            {% if letter.gift.status == 'delivered' %}selected{% endif %}
                            >Доставленно</option>
                            <option value="1"
                            {% if letter.gift.status == 'selected' %}selected{% endif %}
                            >Выбрано</option>
                        </select>
                    </div>
                    <a
                        class="letter-el"
                        href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                    >
                        <button class="inner-button default-button">Подобрать подарок</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% include 'components/footer.html' %}

<script src="{% static 'letters/js/burgerMenu.js' %}"></script>
<script src="{% static 'letters/js/script.js' %}"></script>
<script src="{% static 'usertools/js/changeGiftState.js' %}"></script>

</body>
</html>

letters/templates/letters/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ёлка добра</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/index.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{% static 'letters/css/medias.css' %}">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
</head>
<body>
<p class="popup-message" style="display: none"></p>

<div class="page">
    {% include 'components/user_header.html' %}

    <div class="sub-header high-element block-container">
        <p class="sub-header-el sub-header-title">Ёлка добра</p>
        <p class="sub-header-el sub-header-text">
            Новогодние подарки детям
        </p>
    </div>

    <div class="desc-text-wrapper high-element block-container">
        <div class="desc-img">
            <img class="desc-item desc-img" src="{% static 'letters/images/letters.png' %}">
        </div>
        <div class="desc-img together-img">
            <img class="desc-item together-img" src="{% static 'letters/images/together.png' %}">
        </div>
        <div class="desc-img">
            <img class="desc-item desc-img" src="{% static 'letters/images/about.png' %}">
        </div>
        <div class="desc-item desc-text">
            <p class="desc-inner-text">Акция инициирована волонтерами Уральской Стали при поддержке работников Общества и руководством комбината</p>
            <p class="desc-inner-text">По вопросам акции можно написать на почту или позвонить</p>
        </div>
    </div>

    <div class="letters high-element">
        {% for letter in letters %}
            <div class="letter-container">
                <div class="letter {% if letter.gift.status == 'unselect' %}orange-card{% else %}blue-card{% endif %}">
                    <img class="letter-el letter-img" src="{{ letter.photo.url }}" height="100" width="100">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    {% if letter.gift.status == 'unselect' %}
                        <a onclick="setPopupMessage(event)" data-href="{% url 'usertools:pick_letter' pk=letter.pk %}" class="letter-el add-favorite-link">
                            <button class="default-button inner-button">
                                <span>Выбрать</span>
                            </button>
                        </a>
                        <a
                            class="letter-el"
                            href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                        >
                            <button class="default-button inner-button">
                                <span>Подобрать подарок</span>
                            </button>
                        </a>
                    {% else %}
                        <p class="letter-el">{{ letter.picked_by.first_name }}</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% include 'components/footer.html' %}

<script>
setVisitedMessage(
  'index-visited',
  'Подсказка при первом заходе на страницу'
)
</script>

<script src="{% static 'letters/js/userindex.js' %}"></script>
<script src="{% static 'letters/js/addFavorite.js' %}"></script>
</body>
</html>

letters/templates/letters/letters.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Письма | Ёлка добра</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'usertools/css/selects.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
</head>
<body>
<p class="popup-message" style="display: none"></p>

<div class="page">
    {% include 'components/user_header.html' %}
    <div class="ordering-container">
        <div class="ordering">
            <div class="ordering-banner">
                <img class="ordering-banner-img" src="{% static 'letters/images/order.png' %}">
                <p style="margin-left: .4em">Сортировать</p>
            </div>
            <select class="letter-ordering">
                <option class="ordering-option" value="all">Все</option>
                <option class="ordering-option" value="0">Не выбраные</option>
                <option class="ordering-option" value="1">Выбраные</option>
                <option class="ordering-option" value="2">Доставленые</option>
            </select>
        </div>
    </div>

    <div class="letters high-element">
        {% for letter in letters %}
            <div class="letter-container">
                <div class="letter {% if letter.gift.status == 'unselect' %}orange-card{% else %}blue-card{% endif %}">
                    <img class="letter-el letter-img" src="{{ letter.photo.url }}" height="100" width="100">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    {% if letter.gift.status == 'unselect' %}
                        <a onclick="setPopupMessage(event)" data-href="{% url 'usertools:pick_letter' pk=letter.pk %}" class="letter-el add-favorite-link">
                            <button class="default-button inner-button">
                                <span>Выбрать</span>
                            </button>
                        </a>
                        <a
                            class="letter-el"
                            href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                        >
                            <button class="default-button inner-button">
                                <span>Подобрать подарок</span>
                            </button>
                        </a>
                    {% else %}
                        <p class="letter-el">{{ letter.picked_by.first_name }}</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% include 'components/footer.html' %}

<script>
setVisitedMessage(
  'letters-visited',
  'Подсказка при первом заходе на страницу'
)
document.querySelector('select.letter-ordering').value = '{{ ordering }}'

document.querySelector('select.letter-ordering').addEventListener('change', (event) => {
  let param = event.target.options[event.target.selectedIndex].value
  window.location.href = `${url}/letters/letters/${param}`
})
</script>
<script src="{% static 'letters/js/addFavorite.js' %}"></script>
</body>
</html>

letters/templates/letters/user_letter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Просмотр письма</title>
    <meta name="viewport">

    <link href="{% static 'letters/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" href="{% static 'letters/images/christmasTree.png' %}">
    <link href="{% static 'letters/css/header.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letters.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/hints-swiper.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/medias.css' %}" rel="stylesheet">
    <link href="{% static 'letters/css/letter-detail.css' %}" rel="stylesheet">
</head>

<body>

    <div class="page">
        {% include 'components/user_header.html' %}

        <div class="high-line high-element">
            <div class="back-arrow-on-page-container" onclick="window.history.back()">
                <img class="back-arrow-on-page" src="{% static 'letters/images/back-arrow.png' %}">
            </div>
        </div>

        <div class="letters high-element">
            <div class="letter-container">
                <div class="letter {% if letter.gift.status == 'unselect' %}orange-card{% else %}blue-card{% endif %}">
                    <img class="letter-el letter-img" src="{{ letter.photo.url }}">
                    <p class="letter-el">{{ letter.child.get_full_name }}</p>
                    <p class="letter-el">{{ letter.gift.name }}</p>
                    {% if letter.gift.status == 'unselect' %}
                        <a
                            class="letter-el"
                            href="{% url 'usertools:pick_letter' pk=letter.pk %}"
                        >
                            <button class="default-button inner-button">
                                <span>Выбрать</span>
                            </button>
                        </a>
                        <a
                            class="letter-el"
                            href="{% url 'usertools:recommend_goods' gift_pk=letter.gift.pk %}"
                        >
                            <button class="default-button inner-button">
                                <span>Подобрать подарок</span>
                            </button>
                        </a>
                    {% else %}
                        <p class="letter-el">{{ letter.picked_by.first_name }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% include 'components/footer.html' %}
</body>
</html>